import type { CardDef, EnemyTemplate, EventDef, NodeType, RelicDef } from "./types";

export const CARD_DEFS: Record<string, CardDef> = {
  strike: {
    id: "strike",
    name: "阻断连接",
    type: "attack",
    rarity: "basic",
    cost: 1,
    text: ["造成 6 点伤害。", "造成 9 点伤害。"],
  },
  defend: {
    id: "defend",
    name: "加固规则",
    type: "skill",
    rarity: "basic",
    cost: 1,
    text: ["获得 5 点防护。", "获得 8 点防护。"],
  },
  zhusha: {
    id: "zhusha",
    name: "标记 IOC",
    type: "attack",
    rarity: "basic",
    cost: 1,
    text: ["造成 4 点伤害。施加 1 层 IOC。", "造成 6 点伤害。施加 2 层 IOC。"],
  },
  taomu: {
    id: "taomu",
    name: "批量封禁",
    type: "attack",
    rarity: "common",
    cost: 1,
    text: ["造成 4 点伤害 2 次。", "造成 5 点伤害 2 次。"],
  },
  cloudstep: {
    id: "cloudstep",
    name: "快速 triage",
    type: "skill",
    rarity: "common",
    cost: 0,
    text: ["获得 3 点防护。抽 1 张牌。", "获得 5 点防护。抽 1 张牌。"],
  },
  qingxin: {
    id: "qingxin",
    name: "日志检索",
    type: "skill",
    rarity: "common",
    cost: 0,
    exhaust: true,
    text: ["抽 2 张牌。消耗。", "抽 3 张牌。消耗。"],
  },
  golden: {
    id: "golden",
    name: "临时隔离",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["获得 8 点防护与 1 点算力。", "获得 11 点防护与 1 点算力。"],
  },
  incense: {
    id: "incense",
    name: "分配算力",
    type: "skill",
    rarity: "common",
    cost: 0,
    exhaust: true,
    text: ["获得 2 点算力。消耗。", "获得 3 点算力。消耗。"],
  },
  windScroll: {
    id: "windScroll",
    name: "关联分析",
    type: "skill",
    rarity: "common",
    cost: 0,
    text: ["抽 1 张牌。若目标有 IOC，额外抽 1 张。", "抽 1 张牌。若目标有 IOC，额外抽 2 张。"],
  },
  thunder: {
    id: "thunder",
    name: "沙箱引爆",
    type: "attack",
    rarity: "common",
    cost: 2,
    text: ["造成 10 点伤害。若目标有 IOC，额外造成 6 点伤害。", "造成 14 点伤害。若目标有 IOC，额外造成 8 点伤害。"],
  },
  bell: {
    id: "bell",
    name: "降噪过滤",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["获得 3 点防护。施加 2 层降权。", "获得 5 点防护。施加 3 层降权。"],
  },
  fog: {
    id: "fog",
    name: "还原时间线",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["获得 6 点防护。抽 1 张牌。", "获得 9 点防护。抽 1 张牌。"],
  },
  command: {
    id: "command",
    name: "批量标记",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    text: ["获得 4 点防护。施加 4 层 IOC。", "获得 6 点防护。施加 5 层 IOC。"],
  },
  burn: {
    id: "burn",
    name: "溯源打击",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    text: ["移除所有 IOC。每层造成 5 点伤害。", "移除所有 IOC。每层造成 7 点伤害。"],
  },
  paper: {
    id: "paper",
    name: "部署蜜罐",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["获得 7 点防护。将 1 张蜜罐回刺加入手牌。", "获得 10 点防护。将 1 张强化蜜罐回刺加入手牌。"],
  },
  breakEvil: {
    id: "breakEvil",
    name: "YARA 命中",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    text: ["造成 14 点伤害。若目标有 IOC，获得 1 点能量。", "造成 18 点伤害。若目标有 IOC，获得 1 点能量。"],
  },
  mirror: {
    id: "mirror",
    name: "资产测绘",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["施加 2 层 IOC 与 2 层暴露面。", "施加 3 层 IOC 与 2 层暴露面。"],
  },
  refine: {
    id: "refine",
    name: "超频分析",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    exhaust: true,
    text: ["获得 1 点能量。失去 2 点生命。消耗。", "获得 1 点能量。失去 1 点生命。消耗。"],
  },
  scripture: {
    id: "scripture",
    name: "深度扫描",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["抽 3 张牌，将 1 张噪声告警加入弃牌堆。", "抽 4 张牌，将 1 张噪声告警加入弃牌堆。"],
  },
  ashReturn: {
    id: "ashReturn",
    name: "重放日志",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    text: ["将弃牌堆洗回抽牌堆。抽 1 张牌。获得 4 点防护。", "将弃牌堆洗回抽牌堆。抽 2 张牌。获得 6 点防护。"],
  },
  nightEye: {
    id: "nightEye",
    name: "持续监控",
    type: "power",
    rarity: "rare",
    cost: 1,
    text: ["法门：每回合多抽 1 张牌。", "法门：每回合多抽 1 张牌。立即抽 1 张牌。"],
  },
  citygod: {
    id: "citygod",
    name: "自动化响应",
    type: "power",
    rarity: "rare",
    cost: 2,
    text: ["法门：每回合获得 3 点防护与 1 点算力。", "法门：每回合获得 5 点防护与 1 点算力。"],
  },
  thunderLaw: {
    id: "thunderLaw",
    name: "全域清剿",
    type: "attack",
    rarity: "rare",
    cost: 3,
    text: ["消耗所有算力。造成 12 点伤害，每点算力额外 +5。", "消耗所有算力。造成 16 点伤害，每点算力额外 +6。"],
  },
  paperBlade: {
    id: "paperBlade",
    name: "蜜罐回刺",
    type: "attack",
    rarity: "special",
    cost: 0,
    exhaust: true,
    text: ["造成 3 点伤害。消耗。", "造成 5 点伤害。消耗。"],
  },
  yinCold: {
    id: "yinCold",
    name: "噪声告警",
    type: "status",
    rarity: "status",
    cost: "-",
    unplayable: true,
    text: ["无法打出。回合结束时若在手牌，失去 2 点生命。", "无法打出。回合结束时若在手牌，失去 2 点生命。"],
  },
};

export const CARD_POOL = Object.keys(CARD_DEFS).filter((id) => {
  const rarity = CARD_DEFS[id].rarity;
  return !["basic", "special", "status"].includes(rarity);
});

export const RELICS: RelicDef[] = [
  { id: "bronzeMirror", name: "IOC 情报源", text: "每场战斗开始时，施加 2 层 IOC。" },
  { id: "taomuTassel", name: "封禁热键", text: "每场战斗第一张攻击牌额外造成 4 点伤害。" },
  { id: "citySeal", name: "自动化剧本", text: "每场战斗第一回合获得 2 点算力。" },
  { id: "brokenCenser", name: "WAF 补丁", text: "每打出一张技能牌，获得 1 点防护。" },
  { id: "nightSand", name: "长时日志", text: "每场战斗第一回合多抽 1 张牌。" },
  { id: "oldUmbrella", name: "零信任策略", text: "每场战斗第一回合获得 6 点防护。" },
  { id: "thunderWood", name: "溯源加权", text: "IOC 每层伤害提高 1。" },
  { id: "blankPage", name: "查询缓存", text: "每回合每打出 3 张牌，抽 1 张牌。" },
  { id: "paperHorse", name: "弹性算力", text: "每场战斗第一回合获得 1 点额外能量。" },
  { id: "foxCoin", name: "紧急预算", text: "获得时立即得到 60 预算。", onGain: "gold60" },
];

export const ENEMIES: Record<string, EnemyTemplate> = {
  lantern: {
    id: "lantern",
    name: "端口扫描器",
    artKey: "lantern",
    hp: 42,
    attackChain: "侦察扫描",
    tradecraft: "用 SYN 洪泛和端口指纹快速描出暴露面，再塞入噪声告警拖慢值班节奏。",
    counter: "先用资产测绘/标记 IOC 固定来源，低成本防护挡住探测伤害，再用沙箱引爆收口。",
    moves: [
      { type: "attack", amount: 6, label: "SYN 洪泛" },
      { type: "curse", amount: 1, label: "噪声注入" },
      { type: "block", amount: 7, label: "隐匿端口" },
    ],
  },
  waterghost: {
    id: "waterghost",
    name: "钓鱼载荷",
    artKey: "waterghost",
    hp: 48,
    attackChain: "凭据喷洒",
    tradecraft: "通过钓鱼点击诱导权限授予，再把凭据回传拆成多段小流量绕过阈值。",
    counter: "优先降权和加固规则，避免弱口令扩散；IOC 叠满后用溯源打击清掉回传链路。",
    moves: [
      { type: "attack", amount: 8, label: "钓鱼点击" },
      { type: "debuff", amount: 2, label: "权限诱导" },
      { type: "attack", amount: 5, hits: 2, label: "凭据回传" },
    ],
  },
  templecorpse: {
    id: "templecorpse",
    name: "僵尸进程",
    artKey: "templecorpse",
    hp: 54,
    attackChain: "C2 持久化",
    tradecraft: "僵尸进程保持回连，靠进程守护堆防护，并持续污染日志制造误判。",
    counter: "不要只打伤害；用日志检索和降噪过滤维持抽牌质量，等 IOC 足够后集中清剿。",
    moves: [
      { type: "attack", amount: 10, label: "僵尸回连" },
      { type: "block", amount: 10, label: "进程守护" },
      { type: "curse", amount: 1, label: "日志污染" },
    ],
  },
  macaque: {
    id: "macaque",
    name: "横向移动脚本",
    artKey: "macaque",
    hp: 52,
    attackChain: "横向移动",
    tradecraft: "先横向探测多打点，再用提权脚本抬高后续会话劫持的爆发。",
    counter: "看到提权脚本就提前堆防护或降权，优先阻断连接，别让强度滚起来。",
    moves: [
      { type: "attack", amount: 4, hits: 3, label: "横向探测" },
      { type: "buff", amount: 2, label: "提权脚本" },
      { type: "attack", amount: 10, label: "会话劫持" },
    ],
  },
  warlock: {
    id: "warlock",
    name: "C2 操作员",
    artKey: "warlock",
    hp: 68,
    attackChain: "C2 指挥控制",
    tradecraft: "通过 C2 指令打高额伤害，指挥增强会让下一轮威胁指数迅速上升。",
    counter: "优先标记 IOC 与 YARA 命中；若它开始增强，保留算力给全域清剿。",
    elite: true,
    moves: [
      { type: "attack", amount: 12, label: "C2 指令" },
      { type: "buff", amount: 3, label: "指挥增强" },
      { type: "curse", amount: 2, label: "恶意任务下发" },
    ],
  },
  foxshade: {
    id: "foxshade",
    name: "凭据窃取器",
    artKey: "foxshade",
    hp: 72,
    attackChain: "凭据滥用",
    tradecraft: "凭据抓取造成多段压力，伪装登录降低响应质量，令牌滥用会边打边加固。",
    counter: "用降噪过滤压低攻击强度，配合临时隔离扛住多段伤害，再用批量标记放大处置。",
    elite: true,
    moves: [
      { type: "attack", amount: 8, hits: 2, label: "凭据抓取" },
      { type: "debuff", amount: 3, label: "伪装登录" },
      { type: "blockAttack", amount: 7, block: 10, label: "令牌滥用" },
    ],
  },
  tigerlord: {
    id: "tigerlord",
    name: "勒索核心",
    artKey: "tigerlord",
    hp: 118,
    attackChain: "勒索加密",
    tradecraft: "先全盘加密制造高压，再唤醒僵尸网络抬强度，核心驻留会同时输出和加固。",
    counter: "留足防护应对全盘加密；把 IOC 与算力攒到关键回合，用全域清剿/溯源打击终结。",
    boss: true,
    moves: [
      { type: "attack", amount: 16, label: "全盘加密" },
      { type: "attack", amount: 6, hits: 3, label: "三段破坏" },
      { type: "buff", amount: 3, label: "僵尸网络唤醒" },
      { type: "blockAttack", amount: 10, block: 12, label: "核心驻留" },
    ],
    phases: [
      {
        hpBelow: 0.66,
        label: "密钥横向扩散，攻击从单点加密转为多段破坏",
        moves: [
          { type: "attack", amount: 6, hits: 3, label: "密钥横向扩散" },
          { type: "curse", amount: 1, label: "恢复票据污染" },
          { type: "blockAttack", amount: 10, block: 12, label: "备份目录驻留" },
        ],
      },
      {
        hpBelow: 0.33,
        label: "核心倒计时进入最后压迫，必须用算力或 IOC 终结",
        moves: [
          { type: "attack", amount: 15, label: "核心密钥擦除" },
          { type: "attack", amount: 6, hits: 3, label: "勒索倒计时爆发" },
          { type: "buff", amount: 3, label: "僵尸网络总动员" },
        ],
      },
    ],
  },
};

export const NODE_DEFS: Record<NodeType, { name: string; desc: string }> = {
  combat: { name: "边界告警", desc: "普通攻击活动正在试探防线。处置后获得预算与响应动作。" },
  elite: { name: "高危入侵", desc: "更复杂的攻击链。处置后必定获得一件安全工具。" },
  event: { name: "异常事件", desc: "告警之外还有取舍：误报、业务压力、供应商风险。" },
  rest: { name: "维护窗口", desc: "利用短暂窗口恢复防线，或升级一张响应动作。" },
  shop: { name: "情报市场", desc: "花预算购买响应动作、工具，或清理一条无效规则。" },
  boss: { name: "核心域控", desc: "入侵者正在触达核心域控。天亮前必须阻断。" },
};

export const EVENTS: EventDef[] = [
  {
    id: "well",
    title: "深夜误报告警",
    body: "一条高危告警反复触发，日志上下文却很薄。值班窗口正在被它占满。",
    choices: [
      { id: "wellHeal", title: "快速关闭", desc: "回复 12 点生命。" },
      { id: "wellRelic", title: "深挖上下文", desc: "失去 7 点生命，获得 1 件工具。" },
    ],
  },
  {
    id: "fox",
    title: "灰色情报源",
    body: "匿名情报商递来一个 IOC 包，来源不明，但格式看起来可以直接导入。",
    choices: [
      { id: "foxCard", title: "接收样本", desc: "获得 1 张随机牌。" },
      { id: "foxRemove", title: "清理旧规则", desc: "花费 40 预算，移除 1 张牌。" },
    ],
  },
  {
    id: "temple",
    title: "短暂维护窗口",
    body: "业务方终于给出 15 分钟窗口。你可以升级响应动作，也可以换取更多预算。",
    choices: [
      { id: "templeUpgrade", title: "升级剧本", desc: "升级 1 张牌。" },
      { id: "templeGold", title: "申请预算", desc: "获得 80 预算，将 1 张噪声告警加入牌组。" },
    ],
  },
  {
    id: "scholar",
    title: "供应链请求",
    body: "第三方组件要求临时放行。审批消息很急，但你看见了版本号里不自然的一段空白。",
    choices: [
      { id: "scholarCopy", title: "隔离复现", desc: "复制 1 张非基础牌，并加入 1 张噪声告警。" },
      { id: "scholarLeave", title: "暂不放行", desc: "什么也不发生。" },
    ],
  },
];
